### ISSUE TITLE
CORS settings for images?

### ISSUE THREAD

**Issue by straup** [cooperhewitt/label-book#13]
Images do not load in Firefox. Presumably this is becuase Heroku is expecting CORS settings on the images? This is easy enough to add in S3.

![screen shot 2015-07-10 at 7 33 35 am](https://cloud.githubusercontent.com/assets/54840/8620769/9d1158b0-26d6-11e5-9211-0641c74c1cbb.png)

**Comment by straup** [comment]
See also: https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

**Comment by micahwalter** [comment]
I thought @sambrenner and I already did this, but I'll check.

**Comment by micahwalter** [comment]
It's actually a broken image - https://collection.cooperhewitt.org/objects/18698497/
