### ISSUE TITLE
A better for loop

### ISSUE THREAD

**Issue by micahwalter** [cooperhewitt/label-book#4]
This https://github.com/cooperhewitt/label-book/blob/master/label-book.py#L50-L59 was kind of a quick hack yesterday to make it work.

A better way to do this ( read cleaner ) might be something like this

```
for index in range(len(data)):
    obj_id = data[index]['id']
```

and so on... this way you dont need the i=0 and i=i+1 stuff..

**Comment by AYTAGH** [comment]
merged
